### ISSUE TITLE
Sky Cinema Hits, Sky Cinema Hits HD, One HD

### ISSUE THREAD

**Issue by sundalon** [FrodoVDR/channellogos#2]
Moin Frodo,
im letzten Update fehlt noch der Sender 'Sky Cinema Hits' sowie dessen HD-Ableger.
Außerdem habe ich ein Problem mit der Anzeige des Logos für 'One HD'. Im WebIF
vom epgd wird das Logo passend dargestellt, im OSD des VDR (skindesigner, shadyKISS)
ist es komplett verzerrt. Anbei ein Screenshot.

Cheers,
Ole
![screenshot](https://cloud.githubusercontent.com/assets/18375196/18832620/db7953c2-83ec-11e6-93d2-feb57578be12.jpg)

**Comment by FrodoVDR** [comment]
Sollte behoben sein. Ich musste das Original svg Logo mit Inkscape nachbearbeiten um den Fehler zu beheben.
